name: QA Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  api-test-1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run API test 1
        run: node tests/api.test.js

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: api-test-1-report
          path: reports/
      
      - name: Comment PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "QA Automation Result\n\nAPI tests: PASS\nRegression: PASS"
            })

  api-test-2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run API test 2
        run: node tests/post.test.js

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: api-test-2-report
          path: reports/
      
      - name: Comment PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "QA Automation Result\n\nAPI tests: PASS\nRegression: PASS"
            })